name: CUPS Print Server
version: "1.2.0"
slug: cups-sane-v2
description: The CUPS (Common UNIX Printing System) print server package with drivers included and Avahi and SANE scanner support.
url: https://github.com/vtechs-ja/ha-cups-sane-addon
arch:
  - aarch64
  - armhf
  - armv7
  - amd64
  - i386
usb: true
init: false
homeassistant_api: true
host_network: true
panel_icon: mdi:printer
icon: icon.png
logo: icon.png
ports:
  631/tcp: 631
  631/udp: 631
  8080/tcp: 8080
ports_description:
  631/tcp: Used by other devices on the local network to post print jobs to this server (TCP)
  631/udp: Used by other devices on the local network to post print jobs to this server (UDP)
  8080/tcp: Used to expose ScanServer web interface (TCP)
ingress: true
ingress_port: 8080
map:
  - config:rw
  - ssl
